[context.deploy-preview]
  command = "npm run generate:noindex"

[context.branch-deploy]
  command = "npm run generate:noindex"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/"
  to = "/es-ES/"
  status = 200
  force = true
  conditions = {Language = ["es"]}
