AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Render:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      Handler: index.handler
      Runtime: nodejs8.10
